import { IPayment } from "@/types/payemnt";

export const paymentMocks: IPayment[] = [
  {
    id: 1,
    message: "Pagamento de mensalidade",
    status: "Confirmado",
    createdAt: "12, Julho, 2025",
    amount: 15000,
    method: "Express",
    file: "https://example.com/recibos/recibo1.pdf",
  },
  {
    id: 2,
    message: "Pagamento de curso online",
    status: "Pendente",
    createdAt: "10, Julho, 2025",
    amount: 25000,
    method: "Referência",
    file: "https://example.com/recibos/recibo2.pdf",
  },
  {
    id: 3,
    message: "Renovação de assinatura",
    status: "Cancelado",
    createdAt: "05, Julho, 2025",
    amount: 8000,
    method: "Transferência",
    file: "https://example.com/recibos/recibo3.pdf",
  },
  {
    id: 4,
    message: "Pagamento de consulta",
    status: "Confirmado",
    createdAt: "08, Julho, 2025",
    amount: 10000,
    method: "Express",
    file: "https://example.com/recibos/recibo4.pdf",
  },
  {
    id: 5,
    message: "Pagamento de workshop",
    status: "Confirmado",
    createdAt: "15, Julho, 2025",
    amount: 20000,
    method: "Referência",
    file: "https://example.com/recibos/recibo5.pdf",
  },
  {
    id: 6,
    message: "Inscrição em evento",
    status: "Pendente",
    createdAt: "13, Julho, 2025",
    amount: 18000,
    method: "Transferência",
    file: "https://example.com/recibos/recibo6.pdf",
  },
  {
    id: 7,
    message: "Mensalidade plataforma",
    status: "Cancelado",
    createdAt: "01, Julho, 2025",
    amount: 12000,
    method: "Express",
    file: "https://example.com/recibos/recibo7.pdf",
  },
  {
    id: 8,
    message: "Compra de e-book",
    status: "Confirmado",
    createdAt: "16, Julho, 2025",
    amount: 5000,
    method: "Referência",
    file: "https://example.com/recibos/recibo8.pdf",
  },
  {
    id: 9,
    message: "Pagamento pendente",
    status: "Pendente",
    createdAt: "11, Julho, 2025",
    amount: 3000,
    method: "Express",
    file: "https://example.com/recibos/recibo9.pdf",
  },
  {
    id: 10,
    message: "Assinatura anual",
    status: "Confirmado",
    createdAt: "02, Julho, 2025",
    amount: 60000,
    method: "Transferência",
    file: "https://example.com/recibos/recibo10.pdf",
  },
  {
    id: 11,
    message: "Doação para projeto",
    status: "Pendente",
    createdAt: "09, Julho, 2025",
    amount: 7000,
    method: "Referência",
    file: "https://example.com/recibos/recibo11.pdf",
  },
  {
    id: 12,
    message: "Pagamento atrasado",
    status: "Cancelado",
    createdAt: "04, Julho, 2025",
    amount: 15000,
    method: "Express",
    file: "https://example.com/recibos/recibo12.pdf",
  },
  {
    id: 13,
    message: "Curso de React",
    status: "Confirmado",
    createdAt: "06, Julho, 2025",
    amount: 35000,
    method: "Transferência",
    file: "https://example.com/recibos/recibo13.pdf",
  },
  {
    id: 14,
    message: "Compra de módulo",
    status: "Pendente",
    createdAt: "14, Julho, 2025",
    amount: 9000,
    method: "Express",
    file: "https://example.com/recibos/recibo14.pdf",
  },
  {
    id: 15,
    message: "Taxa de inscrição",
    status: "Confirmado",
    createdAt: "07, Julho, 2025",
    amount: 11000,
    method: "Referência",
    file: "https://example.com/recibos/recibo15.pdf",
  },
  {
    id: 16,
    message: "Licença premium",
    status: "Confirmado",
    createdAt: "03, Julho, 2025",
    amount: 45000,
    method: "Transferência",
    file: "https://example.com/recibos/recibo16.pdf",
  },
  {
    id: 17,
    message: "Reembolso parcial",
    status: "Cancelado",
    createdAt: "12, Julho, 2025",
    amount: 5000,
    method: "Express",
    file: "https://example.com/recibos/recibo17.pdf",
  },
  {
    id: 18,
    message: "Taxa de renovação",
    status: "Confirmado",
    createdAt: "13, Julho, 2025",
    amount: 13000,
    method: "Referência",
    file: "https://example.com/recibos/recibo18.pdf",
  },
  {
    id: 19,
    message: "Compra de curso backend",
    status: "Pendente",
    createdAt: "14, Julho, 2025",
    amount: 27000,
    method: "Transferência",
    file: "https://example.com/recibos/recibo19.pdf",
  },
  {
    id: 20,
    message: "Contribuição comunitária",
    status: "Confirmado",
    createdAt: "15, Julho, 2025",
    amount: 10000,
    method: "Express",
    file: "https://example.com/recibos/recibo20.pdf",
  },
];
