import { PaymentDashBoard } from "@/types/payemnt";

export const paymentDashboardMocks: PaymentDashBoard[] = [
  {
    id: 1,
    message: "Pagamento da mensalidade",
    status: "Confirmado",
    createdAt: "12, Julho, 2025",
    amount: 15000,
    method: "Express",
    file: "https://example.com/files/recibo1.pdf",
    user: {
      id: "u1",
      fullname: "Carlos António",
      tel: "923456789",
      profile: "https://i.pravatar.cc/150?img=1",
      status: "Activo",
      points: 120,
      cash: 5000,
    },
  },
  {
    id: 2,
    message: "Inscrição no curso",
    status: "Pendente",
    createdAt: "10, Julho, 2025",
    amount: 25000,
    method: "Referência",
    file: "https://example.com/files/recibo2.pdf",
    user: {
      id: "u2",
      fullname: "Marta João",
      tel: "923123456",
      profile: "https://i.pravatar.cc/150?img=2",
      status: "Desactivo",
      points: 80,
      cash: 3000,
    },
  },
  {
    id: 3,
    message: "Renovação de plano",
    status: "Cancelado",
    createdAt: "05, Julho, 2025",
    amount: 18000,
    method: "Transferência",
    file: "https://example.com/files/recibo3.pdf",
    user: {
      id: "u3",
      fullname: "Francisco Manuel",
      tel: "924112233",
      profile: "https://i.pravatar.cc/150?img=3",
      status: "Activo",
      points: 90,
      cash: 8000,
    },
  },
  {
    id: 4,
    message: "Compra de módulo",
    status: "Confirmado",
    createdAt: "08, Julho, 2025",
    amount: 10000,
    method: "Express",
    file: "https://example.com/files/recibo4.pdf",
    user: {
      id: "u4",
      fullname: "Juliana Mendes",
      tel: "925998877",
      profile: "https://i.pravatar.cc/150?img=4",
      status: "Activo",
      points: 110,
      cash: 9000,
    },
  },
  {
    id: 5,
    message: "Pagamento de evento",
    status: "Confirmado",
    createdAt: "15, Julho, 2025",
    amount: 20000,
    method: "Referência",
    file: "https://example.com/files/recibo5.pdf",
    user: {
      id: "u5",
      fullname: "Tiago André",
      tel: "926776655",
      profile: "https://i.pravatar.cc/150?img=5",
      status: "Desactivo",
      points: 70,
      cash: 2000,
    },
  },
  {
    id: 6,
    message: "Mensalidade paga",
    status: "Pendente",
    createdAt: "13, Julho, 2025",
    amount: 12000,
    method: "Transferência",
    file: "https://example.com/files/recibo6.pdf",
    user: {
      id: "u6",
      fullname: "Vanessa Luz",
      tel: "927334455",
      profile: "https://i.pravatar.cc/150?img=6",
      status: "Activo",
      points: 300,
      cash: 11000,
    },
  },
  {
    id: 7,
    message: "Pagamento de workshop",
    status: "Cancelado",
    createdAt: "01, Julho, 2025",
    amount: 14000,
    method: "Express",
    file: "https://example.com/files/recibo7.pdf",
    user: {
      id: "u7",
      fullname: "João Pedro",
      tel: "928445566",
      profile: "https://i.pravatar.cc/150?img=7",
      status: "Desactivo",
      points: 25,
      cash: 1000,
    },
  },
  {
    id: 8,
    message: "Taxa de emissão",
    status: "Confirmado",
    createdAt: "16, Julho, 2025",
    amount: 5000,
    method: "Referência",
    file: "https://example.com/files/recibo8.pdf",
    user: {
      id: "u8",
      fullname: "Isabel Costa",
      tel: "929778899",
      profile: "https://i.pravatar.cc/150?img=8",
      status: "Activo",
      points: 400,
      cash: 13000,
    },
  },
  {
    id: 9,
    message: "Compra de material",
    status: "Pendente",
    createdAt: "11, Julho, 2025",
    amount: 3000,
    method: "Express",
    file: "https://example.com/files/recibo9.pdf",
    user: {
      id: "u9",
      fullname: "Ricardo Lima",
      tel: "930223344",
      profile: "https://i.pravatar.cc/150?img=9",
      status: "Desactivo",
      points: 5,
      cash: 100,
    },
  },
  {
    id: 10,
    message: "Assinatura anual",
    status: "Confirmado",
    createdAt: "02, Julho, 2025",
    amount: 60000,
    method: "Transferência",
    file: "https://example.com/files/recibo10.pdf",
    user: {
      id: "u10",
      fullname: "Tatiana Ramos",
      tel: "931667788",
      profile: "https://i.pravatar.cc/150?img=10",
      status: "Activo",
      points: 250,
      cash: 8500,
    },
  },
  // ... repita para até 20 se quiser, posso completar também
];
