import IRoute from "@/types/route";
export const mockRoutes: IRoute[] = [
  {
    id: 1,
    from: "Luanda",
    to: "Viana",
    users: 4,
    distance: "18 km",
    date: "12 , Julho , 2025",
    status: "Aberta",
  },
  {
    id: 2,
    from: "Talatona",
    to: "Benfica",
    users: 2,
    distance: "12 km",
    date: "10 , Julho , 2025",
    status: "Fechada",
  },
  {
    id: 3,
    from: "Kilamba",
    to: "Cacuaco",
    users: 5,
    distance: "22 km",
    date: "9 , Julho , 2025",
    status: "Cancelada",
  },
  {
    id: 4,
    from: "Maianga",
    to: "Ingombota",
    users: 3,
    distance: "6 km",
    date: "8 , Julho , 2025",
    status: "Aberta",
  },
  {
    id: 5,
    from: "Cazenga",
    to: "Rangel",
    users: 6,
    distance: "10 km",
    date: "7 , Julho , 2025",
    status: "Fechada",
  },
  {
    id: 6,
    from: "Cacuaco",
    to: "Zango",
    users: 2,
    distance: "15 km",
    date: "6 , Julho , 2025",
    status: "Aberta",
  },
  {
    id: 7,
    from: "Benfica",
    to: "Cidade Alta",
    users: 3,
    distance: "8 km",
    date: "5 , Julho , 2025",
    status: "Cancelada",
  },
  {
    id: 8,
    from: "Kilamba",
    to: "Sambizanga",
    users: 1,
    distance: "19 km",
    date: "4 , Julho , 2025",
    status: "Fechada",
  },
  {
    id: 9,
    from: "Zango",
    to: "Viana",
    users: 4,
    distance: "14 km",
    date: "3 , Julho , 2025",
    status: "Aberta",
  },
  {
    id: 10,
    from: "Talatona",
    to: "Kilamba",
    users: 5,
    distance: "20 km",
    date: "2 , Julho , 2025",
    status: "Fechada",
  },
  {
    id: 11,
    from: "Maianga",
    to: "Cazenga",
    users: 3,
    distance: "9 km",
    date: "1 , Julho , 2025",
    status: "Cancelada",
  },
  {
    id: 12,
    from: "Cidade Alta",
    to: "Rangel",
    users: 2,
    distance: "7 km",
    date: "30 , Junho , 2025",
    status: "Aberta",
  },
  {
    id: 13,
    from: "Sambizanga",
    to: "Talatona",
    users: 4,
    distance: "17 km",
    date: "29 , Junho , 2025",
    status: "Fechada",
  },
  {
    id: 14,
    from: "Rangel",
    to: "Kilamba",
    users: 6,
    distance: "21 km",
    date: "28 , Junho , 2025",
    status: "Cancelada",
  },
  {
    id: 15,
    from: "Luanda",
    to: "Zango",
    users: 3,
    distance: "25 km",
    date: "27 , Junho , 2025",
    status: "Aberta",
  },
];